site_name: Localizing Apps
pages:
    - Home: index.md
    - Abstracts: abstracts.md
    - Sample: sample.md
    - Courses: courses.md
    - Reviews: reviews.md 
    - Links: links.md
    - Code: code.md
theme:
    name: null
    custom_dir: 'custom_theme'
copyright: Johann Roturier
